version: '3.4'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
    ports:
      - "1433:1433"
    restart: always

  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    image: espasyo-webapi
    ports:
      - "8080:8080"
    depends_on:
      - sqlserver

  console:
    build:
      context: ./espasyo_console  # Adjust if your console project is in a different folder
      dockerfile: Dockerfile      # Make sure your console project contains a proper Dockerfile
    image: espasyo_console
    depends_on:
      - sqlserver
      - webapi
    command: ["dotnet", "run", "--project", "espasyo_console/espasyo_console.csproj"]
    restart: "no"