// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using espasyo.Infrastructure.Data;

#nullable disable

namespace espasyo.Infrastructure.Data.Migrations.Sqlite
{
    [DbContext(typeof(SqliteApplicationDbContext))]
    [Migration("20260511100554_AddAnalysisAndManpowerEntities")]
    partial class AddAnalysisAndManpowerEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("espasyo.Domain.Entities.AnalysisRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClusterGroupsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<string>("ParametersJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("QualityMetricsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_AnalysisRun_CreatedAt");

                    b.ToTable("AnalysisRun", (string)null);
                });

            modelBuilder.Entity("espasyo.Domain.Entities.ForecastResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("Confidence")
                        .HasColumnType("float");

                    b.Property<int>("CrimeType")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ForecastRunId")
                        .HasColumnType("TEXT");

                    b.Property<double>("LowerBound")
                        .HasColumnType("float");

                    b.Property<int>("Month")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Precinct")
                        .HasColumnType("INTEGER");

                    b.Property<double>("PredictedValue")
                        .HasColumnType("float");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Trend")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<double>("UpperBound")
                        .HasColumnType("float");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ForecastRunId")
                        .HasDatabaseName("IX_ForecastResult_ForecastRunId");

                    b.HasIndex("ForecastRunId", "Precinct", "Month", "Year")
                        .HasDatabaseName("IX_ForecastResult_Run_Precinct_Month_Year");

                    b.ToTable("ForecastResult", (string)null);
                });

            modelBuilder.Entity("espasyo.Domain.Entities.ForecastRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("ConfidenceLevel")
                        .HasColumnType("float");

                    b.Property<string>("GeneratedById")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<int>("Horizon")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ModelType")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PrecinctId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RunAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalSeries")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("PrecinctId");

                    b.HasIndex("RunAt")
                        .HasDatabaseName("IX_ForecastRun_RunAt");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_ForecastRun_Status");

                    b.ToTable("ForecastRun", (string)null);
                });

            modelBuilder.Entity("espasyo.Domain.Entities.Incident", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AdditionalInformation")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("CaseId")
                        .HasColumnType("TEXT");

                    b.Property<int>("CrimeType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Motive")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PrecinctId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SanitizedAddress")
                        .HasColumnType("TEXT");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TimeStamp")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("IncidentDateTime");

                    b.Property<int>("Weather")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("_latitude")
                        .HasColumnType("REAL")
                        .HasColumnName("Latitude");

                    b.Property<double?>("_longitude")
                        .HasColumnType("REAL")
                        .HasColumnName("Longitude");

                    b.Property<int>("_month")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Month");

                    b.Property<string>("_timeOfDay")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("TimeOfDay");

                    b.Property<long>("_timestampInUnix")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TimestampInUnix");

                    b.Property<int>("_year")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Year");

                    b.HasKey("Id");

                    b.HasIndex("CaseId")
                        .IsUnique();

                    b.HasIndex("PrecinctId");

                    b.ToTable("Incident", (string)null);
                });

            modelBuilder.Entity("espasyo.Domain.Entities.Manpower", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("HeadCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastUpdated")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<Guid>("PrecinctId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Shift")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PrecinctId", "Shift")
                        .IsUnique()
                        .HasDatabaseName("IX_Manpower_PrecinctId_Shift");

                    b.ToTable("Manpower", (string)null);
                });

            modelBuilder.Entity("espasyo.Domain.Entities.ManpowerRecommendation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<float>("ComplexityScore")
                        .HasColumnType("real");

                    b.Property<float>("Confidence")
                        .HasColumnType("real");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ForecastRunId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Justification")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PrecinctId")
                        .HasColumnType("TEXT");

                    b.Property<float>("PredictedWorkloadHours")
                        .HasColumnType("real");

                    b.Property<int>("RecommendedHeadCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Shift")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ForecastRunId")
                        .HasDatabaseName("IX_ManpowerRecommendation_ForecastRunId");

                    b.HasIndex("PrecinctId");

                    b.ToTable("ManpowerRecommendation", (string)null);
                });

            modelBuilder.Entity("espasyo.Domain.Entities.Precinct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("AreaKm2")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Barangay")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactInfo")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(10,8)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(11,8)");

                    b.Property<int?>("Population")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Barangay")
                        .IsUnique()
                        .HasDatabaseName("IX_Precinct_Barangay");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_Precinct_Code");

                    b.ToTable("Precinct", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            AreaKm2 = 23.5m,
                            Barangay = 0,
                            Code = "ALB",
                            CreatedAt = "2025-01-01T00:00:00.0000000+00:00",
                            Description = "Commercial and business district",
                            IsActive = true,
                            Population = 54000
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            AreaKm2 = 8.2m,
                            Barangay = 7,
                            Code = "AAL",
                            CreatedAt = "2025-01-01T00:00:00.0000000+00:00",
                            Description = "High-income residential area",
                            IsActive = true,
                            Population = 25000
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            AreaKm2 = 15.7m,
                            Barangay = 8,
                            Code = "SUC",
                            CreatedAt = "2025-01-01T00:00:00.0000000+00:00",
                            Description = "Mixed residential and commercial area",
                            IsActive = true,
                            Population = 42000
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            AreaKm2 = 5.3m,
                            Barangay = 4,
                            Code = "POB",
                            CreatedAt = "2025-01-01T00:00:00.0000000+00:00",
                            Description = "City center and administrative area",
                            IsActive = true,
                            Population = 18000
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            AreaKm2 = 12.8m,
                            Barangay = 5,
                            Code = "PUT",
                            CreatedAt = "2025-01-01T00:00:00.0000000+00:00",
                            Description = "Residential area with moderate density",
                            IsActive = true,
                            Population = 35000
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            AreaKm2 = 10.4m,
                            Barangay = 6,
                            Code = "TUN",
                            CreatedAt = "2025-01-01T00:00:00.0000000+00:00",
                            Description = "Residential with some commercial areas",
                            IsActive = true,
                            Population = 28000
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            AreaKm2 = 8.9m,
                            Barangay = 3,
                            Code = "CUP",
                            CreatedAt = "2025-01-01T00:00:00.0000000+00:00",
                            Description = "Smaller residential area",
                            IsActive = true,
                            Population = 22000
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            AreaKm2 = 11.6m,
                            Barangay = 1,
                            Code = "BAY",
                            CreatedAt = "2025-01-01T00:00:00.0000000+00:00",
                            Description = "Residential area",
                            IsActive = true,
                            Population = 31000
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            AreaKm2 = 9.8m,
                            Barangay = 2,
                            Code = "BUL",
                            CreatedAt = "2025-01-01T00:00:00.0000000+00:00",
                            Description = "Residential area",
                            IsActive = true,
                            Population = 26000
                        });
                });

            modelBuilder.Entity("espasyo.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("espasyo.Domain.Entities.Street", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PrecinctId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Street_Name");

                    b.HasIndex("PrecinctId")
                        .HasDatabaseName("IX_Street_PrecinctId");

                    b.ToTable("Street", (string)null);
                });

            modelBuilder.Entity("espasyo.Domain.Entities.UserForecastPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("DefaultConfidenceLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.94999999999999996);

                    b.Property<int>("DefaultHorizon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(6);

                    b.Property<string>("DefaultModelType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("SSA");

                    b.Property<bool>("EnabledTimeAnimation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("PreferredCrimeTypes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreferredPrecincts")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("PreferredTopN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(10);

                    b.Property<bool>("ShowEnsembleView")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("ShowHotspotTimeline")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_UserForecastPreference_UserId");

                    b.ToTable("UserForecastPreference", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("espasyo.Domain.Entities.ForecastResult", b =>
                {
                    b.HasOne("espasyo.Domain.Entities.ForecastRun", "ForecastRun")
                        .WithMany()
                        .HasForeignKey("ForecastRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ForecastResult_ForecastRun");

                    b.Navigation("ForecastRun");
                });

            modelBuilder.Entity("espasyo.Domain.Entities.ForecastRun", b =>
                {
                    b.HasOne("espasyo.Domain.Entities.Precinct", "Precinct")
                        .WithMany()
                        .HasForeignKey("PrecinctId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ForecastRun_Precinct");

                    b.Navigation("Precinct");
                });

            modelBuilder.Entity("espasyo.Domain.Entities.Incident", b =>
                {
                    b.HasOne("espasyo.Domain.Entities.Precinct", "Precinct")
                        .WithMany("Incidents")
                        .HasForeignKey("PrecinctId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Incident_Precinct");

                    b.Navigation("Precinct");
                });

            modelBuilder.Entity("espasyo.Domain.Entities.Manpower", b =>
                {
                    b.HasOne("espasyo.Domain.Entities.Precinct", "Precinct")
                        .WithMany("ManpowerAllocations")
                        .HasForeignKey("PrecinctId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Manpower_Precinct");

                    b.Navigation("Precinct");
                });

            modelBuilder.Entity("espasyo.Domain.Entities.ManpowerRecommendation", b =>
                {
                    b.HasOne("espasyo.Domain.Entities.ForecastRun", "ForecastRun")
                        .WithMany()
                        .HasForeignKey("ForecastRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ManpowerRecommendation_ForecastRun");

                    b.HasOne("espasyo.Domain.Entities.Precinct", "Precinct")
                        .WithMany()
                        .HasForeignKey("PrecinctId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ManpowerRecommendation_Precinct");

                    b.Navigation("ForecastRun");

                    b.Navigation("Precinct");
                });

            modelBuilder.Entity("espasyo.Domain.Entities.Street", b =>
                {
                    b.HasOne("espasyo.Domain.Entities.Precinct", "Precinct")
                        .WithMany("Streets")
                        .HasForeignKey("PrecinctId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Street_Precinct");

                    b.Navigation("Precinct");
                });

            modelBuilder.Entity("espasyo.Domain.Entities.Precinct", b =>
                {
                    b.Navigation("Incidents");

                    b.Navigation("ManpowerAllocations");

                    b.Navigation("Streets");
                });
#pragma warning restore 612, 618
        }
    }
}
